# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-03 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180515_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
