# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-23 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180721_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecomment',
            old_name='image_id',
            new_name='imageId',
        ),
        migrations.AlterField(
            model_name='imagecomment',
            name='imageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.imageModel'),
        ),
    ]
