# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-30 18:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20180723_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='tableChartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField(null=True)),
                ('plot_type', models.CharField(max_length=20)),
                ('plot_data', jsonfield.fields.JSONField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='imagecomment',
            name='imageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.imageModel'),
        ),
    ]
