# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-28 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180808_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomment',
            name='imageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.imageModel'),
        ),
    ]
