# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-14 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20180828_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='userQuesAnswerTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionIDbyPage', models.IntegerField(null=True)),
                ('answer', jsonfield.fields.JSONField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='imagecomment',
            name='imageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.imageModel'),
        ),
        migrations.AlterUniqueTogether(
            name='imagemodel',
            unique_together=set([('posted_by', 'id')]),
        ),
    ]
